### ISSUE TITLE
we can't use multi tools with gears

### ISSUE THREAD

**Issue by farfadet46** [cdqwertz/automation#2]
![screenshot](https://cloud.githubusercontent.com/assets/11613522/17275896/a9f32cca-5718-11e6-92d0-e6b2169ca884.png)

the quarry (1) works
the (2) works too (it's the first placed
but the (3) and (4) don't

**Comment by cdqwertz** [comment]
For me 2,3 and 4 dont work. They dont work because they do not get enough power. The bevel gear splits up the energy it receives from the steam engine. 
`220-1-1 = 218`
`218/3 = 72.6666`
`72.6666 < 100`
